### ISSUE TITLE
Variable in group chat do not work properly

### ISSUE THREAD

**Issue by ehsrrr** [TBXark/ChatGPT-Telegram-Workers#166]
Variable in group chat do not work properly

**Comment by TBXark** [comment]
1. Configure `GROUP_CHAT_BOT_ENABLE` to `true`
2. Configure `TELEGRAM_BOT_NAME`, robot name `xxx_bot`, the order must be the same as `TELEGRAM_AVAILABLE_TOKENS`, must be set, otherwise it cannot be used in group chat
3. Group ID must be added to the whitelist before `CHAT_GROUP_WHITE_LIST` can be used, otherwise anyone can add your robot to the group and consume your quota.
4. According to the privacy security policy of restricted TG, if your group is a public group or more than 2000 people, please set the robot as an administrator, otherwise the robot will not be able to respond to @ robot chat messages.

5. `/setprivacy` must be set to Disable in botfather, otherwise the robot will not be able to respond to @ robot chat messages.

**Comment by romoooly** [comment]
Everything is ok, can use to / to chat with gpt ? its work with @botname

**Comment by TBXark** [comment]
`/setenv SYSTEM_INIT_MESSAGE=you init message`
